name: Docker Ubuntu Intel
# triggered events (push, pull_request) for the develop branch
on:
  push:
    branches: [ develop, main ]
  pull_request:
    branches: [ develop, main ]
  workflow_dispatch:

jobs:

  docker_build:
    name: Docker Intel Build
    runs-on: ubuntu-20.04

    steps:
    # Checkout repository
    - name: Checkout Repository
      uses: actions/checkout@v2

    # Get the Intel oneapi container
    - name: Get the Intel Oneapi Container
      run: docker pull noaagsl/ubuntu-intel-oneapi

    # Start the container
    - name: Start the Intel Oneapi Container
      run: docker run -d -t --name intel-oneapi -v /home/runner/work/SENA-shallow-water/SENA-shallow-water:/SENA-shallow-water/ noaagsl/ubuntu-intel-oneapi

    # Test GT4PY option
    - name: Test Shallow Water GT4PY
      run: docker exec intel-oneapi bash -c "cd SENA-shallow-water; mkdir build; cd build; cmake .. -DCMAKE_BUILD_TYPE=debug -DGT4PY=on; make VERBOSE=1; ctest --output-on-failure"

    # Test GT4PY implementation
    - name: Test Shallow Water GT4PY implementation non-MPI tests
      run: docker exec intel-oneapi bash -c "cd SENA-shallow-water/test/python; mpiexec -n 1 python3 -m pytest -s"
    - name: Test Shallow Water GT4PY implementation MPI serial
      run: docker exec intel-oneapi bash -c "cd SENA-shallow-water/test/python; mpiexec -n 1 python3 -m pytest --with-mpi -s"
    - name: Test Shallow Water GT4PY implementation MPI 2 ranks
      run: docker exec intel-oneapi bash -c "cd SENA-shallow-water/test/python; mpiexec -n 2 python3 -m pytest --with-mpi -s"
    - name: Test Shallow Water GT4PY implementation MPI 4 ranks
      run: docker exec intel-oneapi bash -c "cd SENA-shallow-water/test/python; mpiexec -n 4 python3 -m pytest --with-mpi -s"
    - name: Test Shallow Water GT4PY implementation MPI 9 ranks
      run: docker exec intel-oneapi bash -c "cd SENA-shallow-water/test/python; mpiexec -n 9 python3 -m pytest --with-mpi -s"

# Test debug mode
    - name: Test Shallow Water Debug
      run: docker exec intel-oneapi bash -c "cd SENA-shallow-water; mkdir build; cd build; cmake .. -DCMAKE_BUILD_TYPE=debug; make VERBOSE=1; ctest --output-on-failure"

    # Test release mode
    - name: Test Shallow Water Release
      run: docker exec intel-oneapi bash -c "cd SENA-shallow-water; cd build; rm -rf *; cmake .. -DCMAKE_BUILD_TYPE=release; make VERBOSE=1; ctest --output-on-failure"
