name: MacOS GNU
# triggered events (push, pull_request) for the develop branch
on:
  push:
    branches: [ develop, main ]
  pull_request:
    branches: [ develop, main ]
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
# This workflow contains multiple jobs for different operating systems
jobs:

  macos_Build:
    name: Mac OS GNU Build
    # The type of runner that the job will run on
    runs-on: macos-latest

    env:
      # Work around bug in OpenMPI: See https://github.com/open-mpi/ompi/issues/6518
      OMPI_MCA_btl: "self,tcp"

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout repository (and LFS objects)
        uses: actions/checkout@v2
      
      # Install OpenMPI
      - name: Install OpenMPI
        run: brew install open-mpi

      # Install netCDF
      - name: Install netCDF 
        run: HOMEBREW_NO_AUTO_UPDATE=1 && brew install netcdf netcdf-fortran
      
      # Get NetCDF versions
      - name: Get NetCDF version
        run: |
          nc-config --version
          nf-config --version

      # Install Boost
      - name: Install Boost
        run: brew install boost

      # Setup Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9' 
      - run: python --version

      # Install Serialbox
      - name: Install Serialbox
        run: |
          git clone https://github.com/eth-cscs/serialbox2.git serialbox
          cd serialbox
          mkdir build
          cd build
          export CC=gcc-11
          export FC=gfortran-11
          cmake ../ -DSERIALBOX_ENABLE_FORTRAN=ON
          make
          make install

      # Test GT4Py option
      - name: Test GT4Py option
        run: |
          rm -rf build
          mkdir build
          cd build
          export CC=gcc-11
          export FC=gfortran-11
          cmake -DCMAKE_BUILD_TYPE=debug -DMPIEXEC_PREFLAGS=--oversubscribe -DGT4PY=on ..
          make
          ctest --output-on-failure

      # Test debug mode 
      - name: Test Shallow Water Debug 
        run: |
          rm -rf build
          mkdir build
          cd build
          export CC=gcc-11
          export FC=gfortran-11
          cmake -DCMAKE_BUILD_TYPE=debug -DMPIEXEC_PREFLAGS=--oversubscribe ..
          make
          ctest --output-on-failure
          
      # Test release mode 
      - name: Test Shallow Water Release
        run: |
          rm -rf build
          mkdir build
          cd build
          export CC=gcc-11
          export FC=gfortran-11
          cmake -DCMAKE_BUILD_TYPE=release -DMPIEXEC_PREFLAGS=--oversubscribe ..
          make
          ctest --output-on-failure
